#? hata beklediğimiz kodları 'try' bloğu içine yazıyoruz.

#try:
#bolunen = int(input('bolunen: '))
#bolen = int (input(bolen:  '))
#result=bolunen/bolen
 
#print(result)
#except ZeroDivisionError as err:
 #print ('bir tam sayı sıfıra bölünemez..!')
 #print (err)



# try:
# #hata beklediğimiz kodları try bloğu içerisine yazıyoruz 
# age=int(input('age: '))
# print(age)
# except ValueError as err:  #? aldığımız hata türünü ayıklıyoruz
# print (err)

# except TypeError as err : # istediğimiz kadar except yazabiliyoruz (hata neyse ona bakar)
# print(err)


# except #! herhangi bir hata türü yazamazsak çekirdek (code) dosyalarındaki tüm hatalara bak anlamına gelir.(bütün hatalara bakar genelde tercih edilmez maliyeti yüksektir)
# print ('herhangi bir hata oluştu..!')


# else:
# print ('expection olmazsa ben çalışırım.') #kod bloğunda hiç hata olmazsa else çalışır 

# finally:
# print('ne olursa olsun çalışırım.') #hata olsa bile çalışır 

# #and user ın hatalarının hepsi pyhton ile düzeltilemez ekran önündeki hatalar için java kullanılır try except kullanabilmek için arka planda olmak gerekir.
